// src/react/Avatar.tsx
import { useMemo, useRef } from 'react';
import { encodeDNA, traitsFromName, renderLayeredSVG, getAvatarCSS } from '../index';

export interface AvatarProps {
  dna?: string;
  name?: string;
  size?: 'sm' | 'lg' | 'xl';
  walking?: boolean;
  talking?: boolean;
  waving?: boolean;
  bw?: boolean;
}

let cssInjected = false;

function injectCSS() {
  if (cssInjected || typeof document === 'undefined') return;
  cssInjected = true;
  const style = document.createElement('style');
  style.id = 'tg-avatar-css';
  style.textContent = getAvatarCSS();
  document.head.appendChild(style);
}

const PX_SIZES = { sm: 3, lg: 8, xl: 14 } as const;

export function Avatar({ dna, name, size = 'lg', walking = false, talking = false, waving = false, bw = false }: AvatarProps) {
  injectCSS();
  const idleDelay = useRef(Math.random() * 3);
  const resolvedDna = useMemo(() => dna ?? encodeDNA(traitsFromName(name ?? 'agent')), [dna, name]);
  const { svg, legFrames } = useMemo(() => renderLayeredSVG(resolvedDna, PX_SIZES[size], bw), [resolvedDna, size, bw]);
  const idle = !walking && !talking && !waving;

  const cls = [
    'tg-avatar',
    idle && 'idle',
    walking && 'walking',
    talking && 'talking',
    waving && 'waving',
    legFrames === 3 && 'walk-3f',
    legFrames === 4 && 'walk-4f',
    size === 'sm' && 'tg-avatar-sm',
  ].filter(Boolean).join(' ');

  return (
    <div
      className={cls}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        '--tg-idle-delay': `${idleDelay.current}s`,
        ...(size === 'sm' ? { width: 27, height: 27, overflow: 'hidden' } : {}),
      } as React.CSSProperties}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

// src/vue/Avatar.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { encodeDNA, traitsFromName, renderLayeredSVG, getAvatarCSS } from '../index.ts';

const props = withDefaults(defineProps<{
  dna?: string;
  name?: string;
  size?: 'sm' | 'lg' | 'xl';
  walking?: boolean;
  talking?: boolean;
  waving?: boolean;
  bw?: boolean;
}>(), {
  size: 'lg',
  walking: false,
  talking: false,
  waving: false,
  bw: false,
});

const PX_SIZES = { sm: 3, lg: 8, xl: 14 } as const;

let cssInjected = false;
onMounted(() => {
  if (cssInjected || typeof document === 'undefined') return;
  cssInjected = true;
  const style = document.createElement('style');
  style.id = 'tg-avatar-css';
  style.textContent = getAvatarCSS();
  document.head.appendChild(style);
});

const idleDelay = Math.random() * 3;

const resolvedDna = computed(() =>
  props.dna ?? encodeDNA(traitsFromName(props.name ?? 'agent'))
);
const rendered = computed(() =>
  renderLayeredSVG(resolvedDna.value, PX_SIZES[props.size], props.bw)
);
const idle = computed(() => !props.walking && !props.talking && !props.waving);
</script>

<template>
  <div
    class="tg-avatar"
    :class="{
      idle: idle,
      walking: props.walking,
      talking: props.talking,
      waving: props.waving,
      'walk-3f': rendered.legFrames === 3,
      'walk-4f': rendered.legFrames === 4,
      'tg-avatar-sm': props.size === 'sm',
    }"
    :style="{ '--tg-idle-delay': `${idleDelay}s` }"
    v-html="rendered.svg"
  />
</template>

<style scoped>
.tg-avatar {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
.tg-avatar-sm {
  width: 27px;
  height: 27px;
  overflow: hidden;
}
.tg-avatar-sm :deep(svg) {
  width: 27px;
  height: 27px;
}
</style>
